version: '3.7'

networks:
    traefik-public:
        external: true
#  interna:
#    external: false

services:
    laravel:
        #nome do container definido usando o valor da variável
        container_name: laravel-php8.1
        #build:
        #  context: .
        #  dockerfile: ./Dockerfile
        image: gbzzz/laravel-php8.1
        #image: nginxdemos/hello
        restart: unless-stopped
        ports:
            - 8080:80
        networks:
            - traefik-public
        #     - interna
        #seção onde é definida a montagem bind para o volume da aplicação em desenvolvimento
        #Necessário mapear diretório do host que contém a aplicação a ser desenvolvida
        volumes:
            - ${DIR}:/app
        environment:
            - APP_ENV=local
        labels:
            - traefik.enable=true
            - traefik.network=traefik-public
            #definição da porta de entrada do traefik proxy
            - traefik.http.routers.laravel-rtr.entrypoints=websecure
            - traefik.http.routers.laravel-rtr.tls=true
            - traefik.http.routers.laravel-rtr.tls.certresolver=letsencrypt
            - traefik.http.services.laravel-svc.loadbalancer.server.port=80

            # - traefik.http.routers.laravel-rtr.entrypoints=web
            # - traefik.http.services.laravel-svc.loadbalancer.server.port=80

            - traefik.http.routers.laravel-rtr.rule=Host(`${APP}`)
